### ISSUE TITLE
please review Loglevel on missing zonefile

### ISSUE THREAD

**Issue by andreasschulze** [NLnetLabs/nsd#176]
already [asked on nsd-users](https://lists.nlnetlabs.nl/pipermail/nsd-users/2021-January/002943.html)

```
nsd.conf 

zone:
  name: "example."
  zonefile: "/path/to/zonefile"
  # no master
```

if `/path/to/zonefile` does not exist AND there is no `request-xfer` directive, NSD has no chance to serve any data for `example.` 

Currently only a [message on level INFO is logged in this case](https://github.com/NLnetLabs/nsd/blob/2dc0b405f511fd00295095ad79989aed15b9cbee/dbaccess.c#L533). Shouldn't this be prefixed ERROR?
