### ISSUE TITLE
zonefile with $include relative path stopped working

### ISSUE THREAD

**Issue by wtps0n** [NLnetLabs/nsd#343]
OS: FreeBSD 13.x, nsd just upgraded from 4.9.1 to 4.10.0

nsd.conf:
```
[...]
zonesdir: /usr/local/etc/nsd
pattern:
        name: master_zones_local
        zonefile: "master/zones/%z/%s.cf"
        notify: 10.x.x.x sec_key_server_cdnx_home
        provide-xfr: 10.x.x.x sec_key_server_cdnx_home
        outgoing-interface: 10.x.x.x

zone:
        name: v20.aqq.local
        include-pattern: "master_zones_local"

```
and the zonefile itself has:
```
[...]
$INCLUDE        master/common/common-localhost-any.cf;
$INCLUDE        master/common/common.stats.cf;
```
as you can see thats relative path  - also inside /usr/local/etc/nsd

After upgrading I found in nsd.log:
`error: master/zones/local/v20.aqq.local.cf:69: Cannot open master/common/common-localhost-any.cf, no such file
`
zonefile changed to:
`$INCLUDE /usr/local/etc/nsd/master/common/common-localhost-any.cf;
`
and nsd stopped comlaining.

Is it a bug or I missed some new configuration options?

I've tried to find out if I've made some mistakes but I was not able to find any information about this issue.

Thanks a lot for any help.
