### ISSUE TITLE
zone transfer error

### ISSUE THREAD

**Issue by cairoapcampos** [NLnetLabs/nsd#381]
When trying to configure nsd I have an error in zone transfer. Using the ping command I verified that the two servers communicate. Can you help me?

The master server log shows the error:

```
nsd[27236]: error: xfrd: zone 88.168.192.in-addr.arpa: max notify send count reached, 192.168.88.24 unreachable
nsd[27236]: error: xfrd: zone example.com: max notify send count reached, 192.168.88.24 unreachable
``` 

**Software:** Debian 12 and NSD 4.6.1

**Master nsd.conf:**

```
server:
    do-ip4: yes
    port: 8053
    username: nsd
    zonesdir: "/etc/nsd"
    logfile: "/etc/nsd/nsd.log"
    pidfile: "/run/nsd/nsd.pid"
    hide-version: yes

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8952
    server-key-file: "/etc/nsd/nsd_server.key"
    server-cert-file: "/etc/nsd/nsd_server.pem"
    control-key-file: "/etc/nsd/nsd_control.key"
    control-cert-file: "/etc/nsd/nsd_control.pem"

key:
    name: "demokey"
    algorithm: hmac-sha256
    secret: "my-key-here"

pattern:
    name: "tosecondary"
    notify: 192.168.88.24 demokey
    provide-xfr: 192.168.88.24 demokey

zone:
    name: "example.com"
    zonefile: "example.com.zone"
    include-pattern: "tosecondary"

zone:
    name: "88.168.192.in-addr.arpa"
    zonefile: "192.168.88.zone"
    include-pattern: "tosecondary"

``` 

**Slave nsd.conf:**

```
server:
    do-ip4: yes
    port: 8053
    username: nsd
    zonesdir: "/etc/nsd"
    logfile: "/etc/nsd/nsd.log"
    pidfile: "/run/nsd/nsd.pid"
    hide-version: yes

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8952
    server-key-file: "/etc/nsd/nsd_server.key"
    server-cert-file: "/etc/nsd/nsd_server.pem"
    control-key-file: "/etc/nsd/nsd_control.key"
    control-cert-file: "/etc/nsd/nsd_control.pem"

key:
    name: "demokey"
    algorithm: hmac-sha256
    secret: "my-key-here"

pattern:
    name: "fromprimary"
    allow-notify: 192.168.88.19 demokey
    request-xfr: AXFR 192.168.88.19@8053 demokey

zone:
    name: "example.com"
    zonefile: "example.com.zone"
    include-pattern: "fromprimary"

zone:
    name: "88.168.192.in-addr.arpa"
    zonefile: "192.168.88.zone"
    include-pattern: "fromprimary"
```
