### ISSUE TITLE
Zone transfer fails when not using port 53

### ISSUE THREAD

**Issue by PsHyC0** [NLnetLabs/nsd#384]
Have two RHEL boxes running nsd 4.10.1 - primary (192.168.0.26) and secondary (192.168.0.28). Want them to be authoritative for my internal dns. I've changed the name in here to lan.example.ca.

I got the two systems working and the secondary successfully pulls the zone file from the primary when I update the zone file (lan.example.com.zone) over port 53.

config file for primary:

```
server:                                                                               
    port: 53
    interface: 127.0.0.1                                                              
    ip-address:  192.168.0.26
    server-count: 1
    username: nsd
    hide-version: yes         
    logfile: "/var/log/nsd.log"  
    pidfile: "/run/nsd.pid"            
    do-ip4: yes                     
    do-ip6: no
    zonesdir: /etc/nsd/zones    

key:                                    
    name: "secretkey0"
    algorithm: hmac-sha256
    secret: "<REDACTED>"

zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    notify: 192.168.0.28 secretkey0
    provide-xfr: 192.168.0.28 secretkey0
```

The only change on the secondary is the ip-address and the zone file section:

```
zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    allow-notify: 192.168.0.26 secretkey0
    request-xfr: AXFR 192.168.0.26 secretkey0
```

Now I need it to be on a different port (5353) for my setup. I thought I'd only need to update the port, notify and xfr lines to add @5353 but it fails.

So on the primary I have port: 5353 and changed the zone file section:

```
zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    notify: 192.168.0.28@5353 secretkey0
    provide-xfr: 192.168.0.28@5353 secretkey0
```
Error from nsd.log:

```
[2024-09-25 15:54:21.513] nsd[21017]: notice: nsd starting (NSD 4.10.1)
[2024-09-25 15:54:21.561] nsd[21018]: notice: nsd started (NSD 4.10.1), pid 21017
[2024-09-25 15:54:36.578] nsd[21017]: error: xfrd: zone lan.example.ca: max notify send count reached, 192.168.0.28@5353 unreachable
```

On secondary:
```
zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    allow-notify: 192.168.0.26@5353 secretkey0
    request-xfr: AXFR 192.168.0.26@5353 secretkey0
```

Error from nsd.log:
```
[2024-09-25 15:54:56.784] nsd[21191]: notice: nsd starting (NSD 4.10.1)
[2024-09-25 15:54:56.826] nsd[21192]: notice: nsd started (NSD 4.10.1), pid 21191
[2024-09-25 15:54:56.829] nsd[21191]: error: xfrd: zone lan.example.ca received error code REFUSED from 192.168.0.26@5353
[2024-09-25 15:55:13.847] nsd[21191]: error: xfrd: zone lan.example.ca received error code REFUSED from 192.168.0.26@5353
[2024-09-25 15:55:47.863] nsd[21191]: error: xfrd: zone lan.example.ca received error code REFUSED from 192.168.0.26@5353
[2024-09-25 15:56:34.872] nsd[21191]: error: xfrd: zone lan.example.ca received error code REFUSED from 192.168.0.26@5353
[2024-09-25 15:58:05.883] nsd[21191]: error: xfrd: zone lan.example.ca received error code REFUSED from 192.168.0.26@5353
```

I can dig via port 5353 on both boxes from another machine successfully (I had to manually copy over the lan.example.com.zone file from primary to secondary.

running tcpdump I see a bad udp cksum error then "notify Refused*.

16:04:11.013486 IP (tos 0x0, ttl 64, id 23, offset 0, flags [DF], proto UDP (17), length 216) 192.168.0.26.42773 > 192.168.0.28.5353: [udp sum ok] 49294 notify [b2&3=0x2400] [1a] [1au] SOA (QM)? lan.example.ca. lan.example.ca. SOA a.root-servers.net. john.example.ca. 2024092503 10800 3600 604800 86400 ar: secretkey0. ANY TSIG hmac-sha256. fudge=300 maclen=32 origid=49294 error=0 otherlen=0 (188) 
16:04:11.013686 IP (tos 0x0, ttl 64, id 11697, offset 0, flags [none], proto UDP (17), length 123)                
  192.168.0.28.5353 > 192.168.0.26.42773: [bad udp cksum 0x58eb -> 0x95ca!] 49294 notify Refused*- [0q] 0/0/1 ar: secretkey0. ANY TSIG hmac-sha256. fudge=300 maclen=32 orig id=49294 error=0 otherlen=0 (95)

I'm sure I'm missing something really stupid here but any suggestions?

**Comment by PsHyC0** [comment]
Got it figured out. In case anybody gets stuck. 

On the master you don't need to put the port numbers on the notify and provide-xfr lines:

```
zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    notify: 192.168.0.28 secretkey0
    provide-xfr: 192.168.0.28 secretkey0
```

Only need to put the port on the secondary:

```
zone:
    name: lan.example.ca
    zonefile: lan.example.ca.zone
    allow-notify: 192.168.0.26 secretkey0
    request-xfr: AXFR 192.168.0.26@5353 secretkey0
```

It makes sense now that I've written this all out and given it further thought.
