### ISSUE TITLE
Minor typo in configuration documentaiton

### ISSUE THREAD

**Issue by uplime** [NLnetLabs/nsd#405]
Hello, there is a very minor typo in the configuration documentation [found here](https://nsd.docs.nlnetlabs.nl/en/latest/configuration.html#setting-up-a-secondary-zone). The first half of the example zone configuration uses the filename `primaryone.com.zone` instead of `primaryzone.com.zone` (e.g. `one` instead of `zone`):

```
zone:
    # this server is the primary, 192.0.2.1 is the secondary.
    name: primaryzone.com
    zonefile: /etc/nsd/primaryone.com.zone
    notify: 192.0.2.1 NOKEY # NOKEY for testing purposes only
    provide-xfr: 192.0.2.1 NOKEY # NOKEY for testing purposes only
```
