### ISSUE TITLE
[patch] SystemD script for NSD prevents using chroot

### ISSUE THREAD

**Issue by mij** [NLnetLabs/nsd#441]
This may be considered a packaging issue, but I've seen this file is [hosted in NSD's repo](https://github.com/NLnetLabs/nsd/blob/master/contrib/nsd.service), and you'll probably want to either have it right or not at all.

# The issue

The current startup script for systemd works with a basic NSD setup, but breaks when configuring NSD with `chroot:`. The same configuration works fine when starting up NSD manually with `/usr/sbin/nsd`. Log files give no error whatsever beyond "failed to start".

## How to reproduce

1. setup a vanilla ubuntu
2. `apt install nsd`
3. edit `/etc/nsd/nsd.conf` to enable `chroot:` (see example below)
4. prove that the setup works by running NSD manually with `/usr/sbin/nsd`. Then kill NSD.
5. prove that systemd fails to start NSD by running `systemctl restart nsd`

## Sample config

```
server:
        log-only-syslog: yes
        chroot: "/etc/nsd"
        zonesdir: "/etc/nsd/zones"
        zonelistfile: "/etc/nsd/var/db/nsd/zone.list"
        verbosity: 6
        pidfile: "/etc/nsd/var/run/nsd/nsd.pid"
        xfrdfile: "/etc/nsd/var/db/nsd/xfrd.state"
        xfrdir: "/etc/nsd/tmp/"
```

# The problem

The Ubuntu package for NSD is configured to inhibit some syscalls:

```shell
# grep SystemCallFilter /usr/lib/systemd/system/nsd.service 
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @resources
```

(Note the `~` symbol heading the list, making it an exclusion list).

The `@mount` syscall group contains chroot, effectively causing systemd's environment to kill NSD when it attempts to apply its `chroot` configuration.

# The solution

1. remove `@mount` from file `/usr/lib/systemd/system/nsd.service`
2. reload the configuration with `systemctl daemon-reload`
3. restart nsd with `systemctl restart nsd`

You'll also need to replace the service type in `/usr/lib/systemd/system/nsd.service`, since nsd won't be able to communicate with systemd inside the chroot:

```
# /usr/lib/systemd/system/nsd.service

[Service]
Type=simple
# instead of default:
#Type=notify
```
